export const FETCHING_DATA = "FETCHING_DATA"
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS"
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE"
export const FETCHING_DATA_USER_SUCCESS = "FETCHING_DATA_USER_SUCCESS"
export const USER_IS_LOGGED = "USER_IS_LOGGED"
export const CHECK_AUTH = "CHECK_AUTH"

//Constants about the login process
export const LOGGING_USER = "LOGGING_USER"
export const LOGGING_USER_SUCCESS = "LOGGING_USER_SUCCESS"
export const LOGGING_USER_FAILURE = "LOGGING_USER_FAILURE"

//All the routes of the bottom navigation
export const CHANGE_INDEX = "CHANGE_INDEX"
export const LOAD_FONTS = "LOAD_FONTS"